baseURL: https://tomregan.github.io/
languageCode: en-gb
title: tomregan.github.io
paginate: 50
theme: PaperMod

params:
  disableThemeToggle: true
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  disableSpecial1stPost: false
  disableScrollToTop: true
  showtoc: false
  tocopen: false
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: I'm Tom, I make software
menu:
  main:
    - name: Archive
      url: archives/
      weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
