baseURL = "https://tomregan.github.io/"
languageCode = "en-gb"
title = "tomregan.github.io"
theme = "PaperMod"

[pagination]
pagerSize = 50

[params]
disableThemeToggle = true
ShowReadingTime = false
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
disableSpecial1stPost = false
disableScrollToTop = true
showtoc = false
tocopen = false
DateFormat = "2 January 2006"

[params.homeInfoParams]
Title = "Tom Regan"
Content = "Lots of networking and JVM enthusiasm."

[[menu.main]]
name = "Archive"
url = "archives/"
weight = 5

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "tags/"
weight = 10

[security.exec]
allow = [
    "^(dart-)?sass(-embedded)?$",
    "^go$",
    "^npx$",
    "^postcss$",
    "^asciidoctor$"
]

[markup.goldmark.renderer]
unsafe = true